name: Show Commit Message on Push
on: [push]
jobs:
  display-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Display Commit Message
        run: 'echo "Successful push! Commit message: ${{ github.event.head_commit.message }} "'
